Improved messaging

diff --git a/bin/wppublish b/bin/wppublish
--- a/bin/wppublish
+++ b/bin/wppublish
@@ -14,47 +14,52 @@
 
 set -e
 
+echo "STARTING wppublish"
+
 FOLDERNAME=$(basename "$PWD")
 WPPUBLISHFILE=$PWD/_config/wppublish.json
 LOCALUPLOADDIR=~/Downloads
+
+if test -f "$WPPUBLISHFILE"; then
+	HOST=$(cat $WPPUBLISHFILE | jq -r '.host')
+	PORT=$(cat $WPPUBLISHFILE | jq -r '.port')
+	USERNAME=$(cat $WPPUBLISHFILE | jq -r '.username')
+	PASSWORD=$(cat $WPPUBLISHFILE | jq -r '.password')
+	REMOTETHEMESPATH=$(cat $WPPUBLISHFILE | jq -r '.remotethemespath')
+	MOUNTNAME=sftp-mount
+else
+	echo "ABORTING: _config/wppublish.json not found"
+	exit 1
+fi
 
 if git rev-parse --git-dir > /dev/null 2>&1; then
 	git archive --worktree-attributes -o ~/Downloads/$FOLDERNAME.zip HEAD
 	cd ~/Downloads && unzip $FOLDERNAME.zip -d $FOLDERNAME && rm $FOLDERNAME.zip
 
-	if test -f "$WPPUBLISHFILE"; then
-		HOST=$(cat $WPPUBLISHFILE | jq -r '.host')
-		PORT=$(cat $WPPUBLISHFILE | jq -r '.port')
-		USERNAME=$(cat $WPPUBLISHFILE | jq -r '.username')
-		PASSWORD=$(cat $WPPUBLISHFILE | jq -r '.password')
-		REMOTETHEMESPATH=$(cat $WPPUBLISHFILE | jq -r '.remotethemespath')
-		MOUNTNAME=sftp-mount
+	wpsftprm $HOST $PORT $USERNAME $PASSWORD $FOLDERNAME $MOUNTNAME $LOCALUPLOADDIR $REMOTETHEMESPATH
+	echo "\r\r"
+	sleep 3
+	cd $LOCALUPLOADDIR/$MOUNTNAME && rm -rf $FOLDERNAME
+	sleep 3
+	diskutil umount force $LOCALUPLOADDIR/$MOUNTNAME
+	cd $LOCALUPLOADDIR && rm -r $MOUNTNAME
 
-		wpsftprm $HOST $PORT $USERNAME $PASSWORD $FOLDERNAME $MOUNTNAME $LOCALUPLOADDIR $REMOTETHEMESPATH
-		echo "\r\r"
-		sleep 3
-		cd $LOCALUPLOADDIR/$MOUNTNAME && rm -rf $FOLDERNAME
-		sleep 3
-		diskutil umount force $LOCALUPLOADDIR/$MOUNTNAME
-		cd $LOCALUPLOADDIR && rm -r $MOUNTNAME
-
-		wpsftpput $HOST $PORT $USERNAME $PASSWORD $FOLDERNAME $MOUNTNAME $LOCALUPLOADDIR $REMOTETHEMESPATH
-		echo "\r\r"
-
-		URL=$(cat $WPPUBLISHFILE | jq -r '.url')
-
-		if [ ! -z "$URL" ]; then
-			open $URL
-		fi
-
-	else
-		echo "_config/wppublish.json not found."
-	fi
+	wpsftpput $HOST $PORT $USERNAME $PASSWORD $FOLDERNAME $MOUNTNAME $LOCALUPLOADDIR $REMOTETHEMESPATH
+	echo "\r\r"
 
 	cd $LOCALUPLOADDIR && rm -r $FOLDERNAME
 
+	URL=$(cat $WPPUBLISHFILE | jq -r '.url')
+
+	if [ ! -z "$URL" ]; then
+		echo "Opening $URL..."
+		open $URL
+	fi
+
+	echo "FINISHED wppublish"
+
 else
-	echo "Not a git repository"
+	echo "ABORTING: Not a git repository"
 	exit 1
 fi
 
